#!/usr/bin/python

import imp
import _mysql
import sys
import subprocess

try:
	imp.find_module('cherrypy')
	cherryFound = True
except ImportError:
	cherryFound = False



	
def get_latest_scan_id():
	con = _mysql.connect(dbhost, dbuser, dbpass, dbname)
	con.query("SELECT * FROM SecintScans ORDER BY ScanTime DESC LIMIT 1")
	nmapscans = con.use_result()
	scanid = nmapscans.fetch_row()[0][0]
	return scanid
	

def get_services( filter ):
	scanid = get_latest_scan_id()
	derp = _mysql.connect(dbhost, dbuser, dbpass, dbname)
	template = "{0:15}|{1:25}|{2:8}|{3:8}|{4:8}|{5:15}|{6:45}|{7:35}"
	hostcon = _mysql.connect(dbhost, dbuser, dbpass, dbname)
	hostcon.query("SELECT * FROM NmapHosts WHERE ParentScan=" + scanid)
	hostquery = hostcon.use_result()
	
	serviceText = template.format("HostIP", "HostName", "SvcID", "SvcProto", "SvcPort", "ServiceName", "ServiceProduct", "ServiceVersion")
	serviceText = serviceText + "<br>"
	if (filter):
		filterarg = filter
	else:
		filterarg = ''

	while True:
		hostrow = hostquery.fetch_row()
		if (not hostrow):
			break
		hostid = hostrow[0][0]
		filtertext = 'WHERE ParentHost=' + hostid
		derp.query("SELECT * FROM NmapServices " + filtertext)
		servicequery = derp.use_result()

		while True:
			servicerow = servicequery.fetch_row()
			if (not servicerow):
				break
			greptext = hostrow[0][1] + '\t\t' + hostrow[0][4] + '\t\t' + servicerow[0][0] + '\t\t' + servicerow[0][1] + '\t\t' + servicerow[0][2] + '\t\t' + servicerow[0][3] + '\t\t' + servicerow[0][6] + '\t\t' + servicerow[0][7]
			if filterarg in greptext:
				serviceText = serviceText + template.format(hostrow[0][1], hostrow[0][4], servicerow[0][0], servicerow[0][1], servicerow[0][2], servicerow[0][3], servicerow[0][6], servicerow[0][7])
				serviceText = serviceText + "<br>"
	return serviceText




dbhost = "localhost"
dbname = ""
dbuser = ""
dbpass = ""

f = open('secint.conf', 'r')
for line in f:
	line = line.strip('\n')
	linearr = line.split('=')
	if (linearr[0] == "database"):
		dbname = linearr[1]
	elif (linearr[0] == "user"):
		dbuser = linearr[1]
	elif (linearr[0] == "password"):
		dbpass = linearr[1]
	elif (linearr[0] == "host"):
                dbpass = linearr[1]



print "SecInt Web - Powered by CherryPy \r\n"
print "**************************************"



if (cherryFound):

	print "CherryPy Found, starting web server"	

	import cherrypy	

	cherrypy.server.socket_port = 9191
	cherrypy.server.socket_host = '0.0.0.0'
	cherrypy.config.update({ "environment": "embedded" })
	
	class SecIntWeb:
    		def index(self, **args):
			
			pageText = '<html><body>'

			if not args:
					
				pageText = pageText + "Latest Service Data <br>:"

				
				pageText = pageText + get_services('')
								
						

			else:
				if 'd' in args:
					pageText = pageText + "YES"
						

			pageText = pageText + '</body></html>'	
			return pageText
    		
		index.exposed = True	

	cherrypy.quickstart(SecIntWeb())

else:
	print "CherryPy Not Found :( "



